### ISSUE TITLE
Unused variables c_rel_feat_s and latent_obj_vecs in EchoScene.py

### ISSUE THREAD

**Issue by kangx326** [ymxlzgy/echoscene#6]
I've been examining the codebase and stumbled upon a couple of variables that appear to be defined but not subsequently used in model/EchoScene.py. Specifically, c_rel_feat_s defined on line 372 and latent_obj_vecs defined on line 378 do not seem to be utilized within the denoise unet implementations found at model/networks/diffusion_shape/openai_model_3d.py line 844 and model/networks/diffusion_layout/denoise_net.py line 792.

Upon further inspection, it seems that only obj_embed is being used in the block of code from lines 331 to 370 in model/EchoScene.py.

Additionally, I am trying to understand the implementation details of the Manipulation Strategy mentioned in the supplementary materials. Could you please point me to the part of the codebase that corresponds to this strategy?

Thank you for your assistance in clarifying these points. It would be beneficial for the understanding and maintenance of the code.

Best regards,
Xin

**Comment by ymxlzgy** [comment]
You are correct. The initial relation embedding is not used in the current released version of the code. We have a disclaimer in the readme. However, this does not affect performance because graph constraints are taken into account in the denoising process despite starting from `obj_embed`.

The manipulation strategy can be found in the dataloader, where we fake the graph at the very beginning.

**Comment by kangx326** [comment]
I get it. Thanks a lot.
